name: Publish Package

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Version Check
      id: versionCheck
      uses: EndBug/version-check@v1
      with:
        diff-search: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure GitHub Registry
      if: steps.versionCheck.outputs.changed == 'true'
      run: |
        npm config set @neotro:registry https://npm.pkg.github.com/
        npm config set //npm.pkg.github.com/:_authToken ${{ secrets.PACKAGES_TOKEN }}

    - name: Install Dependencies
      if: steps.versionCheck.outputs.changed == 'true'
      run: npm install

    - name: Build
      if: steps.versionCheck.outputs.changed == 'true'
      run: npx tsc -p .

    - name: Publish
      if: steps.versionCheck.outputs.changed == 'true'
      run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }}
